# Generated by Django 5.1.6 on 2025-02-22 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='creation_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='Cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='waterbottle',
            name='Supplied_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.supplier'),
        ),
    ]
