# Generated by Django 5.1.6 on 2025-02-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0002_alter_supplier_creation_time_alter_waterbottle_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='SKU',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
