# Generated by Django 5.1.6 on 2025-02-25 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0004_alter_waterbottle_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
