# Generated by Django 5.1.6 on 2025-02-22 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_name', models.CharField(max_length=100)),
                ('supplier_city', models.CharField(max_length=100)),
                ('supplier_country', models.CharField(max_length=100)),
                ('creation_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterBottle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SKU', models.CharField(max_length=100)),
                ('Brand', models.CharField(max_length=100)),
                ('Cost', models.FloatField()),
                ('Size', models.CharField(max_length=100)),
                ('Mouth_Size', models.CharField(max_length=100)),
                ('Color', models.CharField(max_length=100)),
                ('Supplied_by', models.CharField(max_length=100)),
                ('Current_Quantity', models.IntegerField()),
            ],
        ),
    ]
