# Generated by Django 5.1.6 on 2025-02-22 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0003_alter_waterbottle_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waterbottle',
            name='SKU',
            field=models.CharField(max_length=3, unique=True),
        ),
    ]
