# Generated by Django 5.1.6 on 2025-04-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0005_alter_supplier_supplier_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('pass_word', models.CharField(max_length=50)),
            ],
        ),
    ]
