# Generated by Django 5.1.6 on 2025-11-29 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyInventoryApp', '0006_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_no', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('customer_type', models.CharField(blank=True, max_length=50)),
                ('satisfaction', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='waterbottle',
            name='Supplied_by',
        ),
        migrations.AddField(
            model_name='account',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MyInventoryApp.customer'),
        ),
        migrations.DeleteModel(
            name='Supplier',
        ),
        migrations.DeleteModel(
            name='WaterBottle',
        ),
    ]
